[build]
  command = "npm --prefix 'FuneralHome/induduzo-care-site-main' install && npm --prefix 'FuneralHome/induduzo-care-site-main' run build"
  publish = "FuneralHome/induduzo-care-site-main/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


