[build]
  command = """
  bash -lc '
    echo "PWD=$(pwd)"
    echo "=== searching for package.json (depth ≤ 3) ==="
    APP_DIR=$(find . -maxdepth 3 -type f -name package.json -not -path "*/node_modules/*" -print | head -n1 | xargs dirname)
    echo "APP_DIR=$APP_DIR"
    if [ -z "$APP_DIR" ]; then
      echo "No package.json found within depth 3." && exit 1
    fi
    echo "=== installing ==="
    npm --prefix "$APP_DIR" ci || npm --prefix "$APP_DIR" install
    echo "=== building ==="
    npm --prefix "$APP_DIR" run build
    echo "=== staging publish dir ==="
    rm -rf web_dist && mkdir -p web_dist
    cp -r "$APP_DIR/dist/." web_dist
  '
  """
  publish = "web_dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


