"""Turn a filled-in phone capture sheet into SQL for person_phones.

    python db/seed/load_phone_numbers.py phone_capture.csv > phones.sql

The sheet comes from db/seed/export_phone_capture_sheet.sql. Fill in the `cell`
column, leave everything else alone, and hand it back here.

WHAT IT DOES WITH A NUMBER
Normalises it to E.164 ('0841451245' becomes '+27841451245') so that Twilio can
dial it and so two spellings of one number cannot become two rows. South African
numbers are the assumed case; anything already in '+cc' form is passed through.

WHAT IT REFUSES TO DO
Guess. A number that is not a recognisable South African mobile, landline or
international number is reported to stderr and left out of the SQL, because a
phone number that is silently wrong is worse than one that is visibly absent:
the office believes it can reach a family, and finds out that it cannot at the
moment it matters most.

Rows are written with `on conflict do nothing`, so re-running a sheet after
adding a few more numbers is safe and will not duplicate anything.
"""

from __future__ import annotations

import csv
import re
import sys

TENANT = "00000000-0000-0000-0000-000000000001"
SOURCE = "phone_capture_sheet"


def normalise(raw: str) -> tuple[str | None, str | None]:
    """Return (e164, reason_rejected). Exactly one is None."""
    if not raw or not raw.strip():
        return None, "empty"

    cleaned = raw.strip()
    # Strip anything that is not a digit or a leading plus.
    digits = re.sub(r"[^\d+]", "", cleaned)

    if digits.startswith("+"):
        rest = digits[1:]
        if rest.isdigit() and 8 <= len(rest) <= 15:
            return "+" + rest, None
        return None, f"not a usable international number: {raw!r}"

    if digits.startswith("00"):
        rest = digits[2:]
        if rest.isdigit() and 8 <= len(rest) <= 15:
            return "+" + rest, None
        return None, f"not a usable international number: {raw!r}"

    # 27821234567 -> +27821234567
    if digits.startswith("27") and len(digits) == 11:
        return "+" + digits, None

    # 0821234567 -> +27821234567. This is the overwhelmingly common case.
    if digits.startswith("0") and len(digits) == 10:
        return "+27" + digits[1:], None

    # 821234567, someone dropped the leading zero.
    if len(digits) == 9 and digits[0] in "123456789":
        return "+27" + digits, None

    return None, f"cannot be read as a phone number: {raw!r}"


def is_mobile(e164: str) -> bool:
    """South African mobile prefixes start 06, 07 or 08 after the country code."""
    return bool(re.match(r"^\+27[678]", e164))


def q(value) -> str:
    if value is None or value == "":
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    if len(sys.argv) < 2:
        return print(__doc__) or 1

    statements: list[str] = []
    rejected: list[tuple[str, str, str]] = []
    seen_primary: set[str] = set()
    accepted = 0

    with open(sys.argv[1], newline="", encoding="utf-8-sig") as fh:
        for line, row in enumerate(csv.DictReader(fh), start=2):
            person_id = (row.get("person_id") or "").strip()
            raw = (row.get("cell") or "").strip()
            who = f"{row.get('first_names', '')} {row.get('surname', '')}".strip()

            if not person_id:
                rejected.append((str(line), who, "no person_id on this row"))
                continue
            if not raw:
                continue  # Simply not captured yet. Not an error.

            e164, reason = normalise(raw)
            if e164 is None:
                rejected.append((str(line), who, reason or "unknown"))
                continue

            mobile = is_mobile(e164)
            # The first good number for a person becomes their primary, which is
            # what policy_overview and any "ring this family" screen will use.
            primary = person_id not in seen_primary
            seen_primary.add(person_id)

            statements.append(
                "insert into person_phones (tenant_id, person_id, phone_type, number, "
                "number_raw, is_primary, is_whatsapp, source) values ("
                f"{q(TENANT)}, {q(person_id)}, {q('mobile' if mobile else 'other')}, "
                f"{q(e164)}, {q(raw)}, {q(primary)}, {q(mobile)}, {q(SOURCE)}) "
                "on conflict do nothing;"
            )
            accepted += 1

    out = sys.stdout
    out.write("-- Generated by db/seed/load_phone_numbers.py. Do not edit by hand.\n")
    out.write(f"-- Source: {sys.argv[1]}\n")
    out.write(f"-- {accepted} phone numbers.\n")
    out.write("--\n-- Resolves the matching phone_number_missing flags in the same\n")
    out.write("-- transaction, so the office queue empties as the numbers arrive.\n")
    out.write("begin;\n\n")
    out.write("\n".join(statements))
    out.write("\n\nupdate data_quality_flags f\n")
    out.write("   set resolved_at = now(),\n")
    out.write("       resolved_by = 'phone_capture_sheet',\n")
    out.write("       resolution  = 'Phone number captured.'\n")
    out.write(" where f.issue_code = 'phone_number_missing'\n")
    out.write("   and f.resolved_at is null\n")
    out.write("   and exists (select 1 from person_phones p\n")
    out.write("                where p.person_id = f.person_id and p.archived_at is null);\n")
    out.write("\ncommit;\n")

    print(f"-- accepted {accepted}, rejected {len(rejected)}", file=sys.stderr)
    for line, who, reason in rejected:
        print(f"--   row {line} ({who}): {reason}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
